# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=com.mclegoman
user=mclegoman
slug=luminance
modId=luminance
modName=Luminance
modDescription=Luminance is a library mod that helps with shader rendering, and contains helper classes, and event hooks to help other mods with game rendering.
authors=dannytaylor, Nettakrim
contributors=
license=LGPL-3.0-or-later
# Mod Version
modVersion=1.1.0-alpha.1
# Branch Metadata
branchName=fabric-1.21.11
compatibleVersions=1.21.11
compatibleLoaders=fabric