/*
    Luminance
    Contributor(s): MCLegoMan
    Github: https://github.com/MCLegoMan/Luminance
    Licence: GNU LGPLv3
*/

package com.mclegoman.luminance.client.shaders;

import com.mclegoman.luminance.client.events.Events;
import net.minecraft.entity.effect.StatusEffects;

public class SmoothUniforms extends Uniforms {
	public static float prevViewDistance = getViewDistance(0.0F);
	public static float viewDistance = getViewDistance(0.0F);
	public static float prevFov = getFov(0.0F);
	public static float fov = getFov(0.0F);
	public static float[] prevEyePosition = getEyePosition(0.0F);
	public static float[] eyePosition = getEyePosition(0.0F);
	public static float[] prevPosition = getPosition(0.0F);
	public static float[] position = getPosition(0.0F);
	public static float prevPitch = getPitch(0.0F);
	public static float pitch = getPitch(0.0F);
	public static float prevYaw = getYaw(0.0F);
	public static float yaw = getYaw(0.0F);
	public static float prevCurrentHealth = getCurrentHealth(0.0F);
	public static float currentHealth = getCurrentHealth(0.0F);
	public static float prevMaxHealth = getMaxHealth(0.0F);
	public static float maxHealth = getMaxHealth(0.0F);
	public static float prevCurrentAbsorption = getCurrentAbsorption(0.0F);
	public static float currentAbsorption = getCurrentAbsorption(0.0F);
	public static float prevMaxAbsorption = getMaxAbsorption(0.0F);
	public static float maxAbsorption = getMaxAbsorption(0.0F);
	public static float prevCurrentHurtTime = getCurrentHurtTime(0.0F);
	public static float currentHurtTime = getCurrentHurtTime(0.0F);
	public static float prevMaxHurtTime = getMaxHurtTime(0.0F);
	public static float maxHurtTime = getMaxHurtTime(0.0F);
	public static float prevCurrentAir = getCurrentAir(0.0F);
	public static float currentAir = getCurrentAir(0.0F);
	public static float prevMaxAir = getMaxAir(0.0F);
	public static float maxAir = getMaxAir(0.0F);
	public static float prevIsSprinting = getIsSprinting(0.0F);
	public static float isSprinting = getIsSprinting(0.0F);
	public static float prevIsSwimming = getIsSwimming(0.0F);
	public static float isSwimming = getIsSwimming(0.0F);
	public static float prevIsSneaking = getIsSneaking(0.0F);
	public static float isSneaking = getIsSneaking(0.0F);
	public static float prevIsCrawling = getIsCrawling(0.0F);
	public static float isCrawling = getIsCrawling(0.0F);
	public static float prevIsInvisible = getIsInvisible(0.0F);
	public static float isInvisible = getIsInvisible(0.0F);
	public static float prevIsWithered = getHasEffect(StatusEffects.WITHER);
	public static float isWithered = getHasEffect(StatusEffects.WITHER);
	public static float prevIsPoisoned = getHasEffect(StatusEffects.POISON);
	public static float isPoisoned = getHasEffect(StatusEffects.POISON);
	public static float prevIsBurning = getIsBurning(0.0F);
	public static float isBurning = getIsBurning(0.0F);
	public static float prevIsOnGround = getIsOnGround(0.0F);
	public static float isOnGround = getIsOnGround(0.0F);
	public static float prevIsOnLadder = getIsOnLadder(0.0F);
	public static float isOnLadder = getIsOnLadder(0.0F);
	public static float prevIsRiding = getIsRiding(0.0F);
	public static float isRiding = getIsRiding(0.0F);
	public static float prevHasPassengers = getHasPassengers(0.0F);
	public static float hasPassengers = getHasPassengers(0.0F);
	public static float prevBiomeTemperature = getBiomeTemperature(0.0F);
	public static float biomeTemperature = getBiomeTemperature(0.0F);
	public static float prevAlpha = getAlpha(0.0F);
	public static float alpha = getAlpha(0.0F);
	public static void tick(float tickDelta) {
		prevViewDistance = viewDistance;
		viewDistance = (prevViewDistance + getViewDistance(tickDelta)) * 0.5F;
		prevFov = fov;
		fov = (prevFov + getFov(tickDelta)) * 0.5F;
		prevEyePosition = eyePosition;
		float[] currentEyePosition = getEyePosition(tickDelta);
		eyePosition = new float[]{((prevEyePosition[0] + currentEyePosition[0]) * 0.5F), ((prevEyePosition[1] + currentEyePosition[1]) * 0.5F), ((prevEyePosition[2] + currentEyePosition[2]) * 0.5F)};
		prevPosition = position;
		float[] currentPosition = getPosition(tickDelta);
		position = new float[]{((prevPosition[0] + currentPosition[0]) * 0.5F), ((prevPosition[1] + currentPosition[1]) * 0.5F), ((prevPosition[2] + currentPosition[2]) * 0.5F)};
		prevPitch = pitch;
		pitch = (prevPitch + getPitch(tickDelta)) * 0.5F;
		prevYaw = yaw;
		yaw = (prevYaw + getYaw(tickDelta)) * 0.5F;
		prevCurrentHealth = currentHealth;
		currentHealth = (prevCurrentHealth + getCurrentHealth(tickDelta)) * 0.5F;
		prevMaxHealth = maxHealth;
		maxHealth = (prevMaxHealth + getMaxHealth(tickDelta)) * 0.5F;
		prevCurrentAbsorption = currentAbsorption;
		currentAbsorption = (prevCurrentAbsorption + getCurrentAbsorption(tickDelta)) * 0.5F;
		prevMaxAbsorption = maxAbsorption;
		maxAbsorption = (prevMaxAbsorption + getMaxAbsorption(tickDelta)) * 0.5F;
		prevCurrentHurtTime = currentHurtTime;
		currentHurtTime = (prevCurrentHurtTime + getCurrentHurtTime(tickDelta)) * 0.5F;
		prevMaxHurtTime = maxHurtTime;
		maxHurtTime = (prevMaxHurtTime + getMaxHurtTime(tickDelta)) * 0.5F;
		prevCurrentAir = currentAir;
		currentAir = (prevCurrentAir + getCurrentAir(tickDelta)) * 0.5F;
		prevMaxAir = maxAir;
		maxAir = (prevMaxAir + getMaxAir(tickDelta)) * 0.5F;
		prevIsSprinting = isSprinting;
		isSprinting = (prevIsSprinting + getIsSprinting(tickDelta)) * 0.5F;
		prevIsSwimming = isSwimming;
		isSwimming = (prevIsSwimming + getIsSwimming(tickDelta)) * 0.5F;
		prevIsSneaking = isSneaking;
		isSneaking = (prevIsSneaking + getIsSneaking(tickDelta)) * 0.5F;
		prevIsCrawling = isCrawling;
		isCrawling = (prevIsCrawling + getIsCrawling(tickDelta)) * 0.5F;
		prevIsInvisible = isInvisible;
		isInvisible = (prevIsInvisible + getIsInvisible(tickDelta)) * 0.5F;
		prevIsWithered = isWithered;
		isWithered = (prevIsWithered + getHasEffect(StatusEffects.WITHER)) * 0.5F;
		prevIsPoisoned = isPoisoned;
		isPoisoned = (prevIsPoisoned + getHasEffect(StatusEffects.POISON)) * 0.5F;
		prevIsBurning = isBurning;
		isBurning = (prevIsBurning + getIsBurning(tickDelta)) * 0.5F;
		prevIsOnGround = isOnGround;
		isOnGround = (prevIsOnGround + getIsOnGround(tickDelta)) * 0.5F;
		prevIsOnLadder = isOnLadder;
		isOnLadder = (prevIsOnLadder + getIsOnLadder(tickDelta)) * 0.5F;
		prevIsRiding = isRiding;
		isRiding = (prevIsRiding + getIsRiding(tickDelta)) * 0.5F;
		prevHasPassengers = hasPassengers;
		hasPassengers = (prevHasPassengers + getHasPassengers(tickDelta)) * 0.5F;
		prevBiomeTemperature = biomeTemperature;
		biomeTemperature = (prevBiomeTemperature + getBiomeTemperature(tickDelta)) * 0.5F;
		prevAlpha = alpha;
		alpha = (prevAlpha + getAlpha(tickDelta)) * 0.5F;
	}
	public static void init() {
		Events.ShaderUniform.registerFloat("lu", "viewDistanceSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevViewDistance, viewDistance));
		Events.ShaderUniform.registerFloat("lu", "fovSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevFov, fov));
		Events.ShaderUniform.registerFloats("lu", "eyePositionSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevEyePosition, eyePosition));
		Events.ShaderUniform.registerFloats("lu", "positionSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevPosition, position));
		Events.ShaderUniform.registerFloat("lu", "pitchSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevPitch, pitch));
		Events.ShaderUniform.registerFloat("lu", "yawSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevYaw, yaw));
		Events.ShaderUniform.registerFloat("lu", "currentHealthSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevCurrentHealth, currentHealth));
		Events.ShaderUniform.registerFloat("lu", "maxHealthSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevMaxHealth, maxHealth));
		Events.ShaderUniform.registerFloat("lu", "currentAbsorptionSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevCurrentAbsorption, currentAbsorption));
		Events.ShaderUniform.registerFloat("lu", "maxAbsorptionSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevMaxAbsorption, maxAbsorption));
		Events.ShaderUniform.registerFloat("lu", "currentHurtTimeSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevCurrentHurtTime, currentHurtTime));
		Events.ShaderUniform.registerFloat("lu", "maxHurtTimeSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevMaxHurtTime, maxHurtTime));
		Events.ShaderUniform.registerFloat("lu", "currentAirSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevCurrentAir, currentAir));
		Events.ShaderUniform.registerFloat("lu", "maxAirSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevMaxAir, maxAir));
		Events.ShaderUniform.registerFloat("lu", "isSprintingSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsSprinting, isSprinting));
		Events.ShaderUniform.registerFloat("lu", "isSwimmingSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsSwimming, isSwimming));
		Events.ShaderUniform.registerFloat("lu", "isSneakingSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsSneaking, isSneaking));
		Events.ShaderUniform.registerFloat("lu", "isCrawlingSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsCrawling, isCrawling));
		Events.ShaderUniform.registerFloat("lu", "isInvisibleSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsInvisible, isInvisible));
		Events.ShaderUniform.registerFloat("lu", "isWitheredSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsWithered, isWithered));
		Events.ShaderUniform.registerFloat("lu", "isPoisonedSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsPoisoned, isPoisoned));
		Events.ShaderUniform.registerFloat("lu", "isBurningSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsBurning, isBurning));
		Events.ShaderUniform.registerFloat("lu", "isOnGroundSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsOnGround, isOnGround));
		Events.ShaderUniform.registerFloat("lu", "isOnLadderSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsOnLadder, isOnLadder));
		Events.ShaderUniform.registerFloat("lu", "isRidingSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevIsRiding, isRiding));
		Events.ShaderUniform.registerFloat("lu", "hasPassengersSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevHasPassengers, hasPassengers));
		Events.ShaderUniform.registerFloat("lu", "biomeTemperatureSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevBiomeTemperature, biomeTemperature));
		Events.ShaderUniform.registerFloat("lu", "alphaSmooth", (tickDelta) -> Shaders.getSmooth(tickDelta, prevAlpha, alpha));
	}
}