# relative directories can be awkward to work with
# so this sets an absolute location that all the below directories below will be relative to (if they dont contain a :)
root_directory = "C:/.../luminance"

# (this config.toml does still need to be wherever the running directory of the script is)

# directories of the post shaders that need to be updated
post_effect_directories = [
    # eg "common/src/main/resources/assets/luminance/post_effect"
]
# an ./output/ folder will appear at each of these locations

# directories where all the fsh/vsh files are kept, used to transfer the shader ids and uniforms
# a program id like "minecraft:post/blit" will search all directories matching ".../minecraft/shaders" for a ".../minecraft/shaders/post/blit.json"
shader_directories = [
    "assets/25w07a/vanilla 1.21.4/minecraft/shaders", # vanilla shaders
    "common/src/main/resources/assets/minecraft/shaders", # old super secret settings 
    "common/src/main/resources/assets/luminance/shaders", # luminance's custom shaders
    # if a post effect shader uses custom programs, the directory of those shaders will need to be added here
]

# if the script runs successfully:
# the .json files in the post_effect_directories can be replaced with the ones from their respective ./output/
# and the .json files in the shader_directories can be removed